title: ThingsBoard Learning
description: Learning materials and documentation for ThingsBoard
theme: minima
baseurl: ""
url: ""

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .github/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
